# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.who.smart-ig-upvhproject
canonical: http://worldhealthorganization.github.io/smart-ig-upvhproject
name: smart-ig-upvhproject
status: draft
version: 0.2.1
fhirVersion: 4.0.1
date: 2022-10-25
# copyright:
copyrightYear: 2021+
releaseLabel: "CI Build"
title: "University of the Philippines Manila Viral Hepatitis Project Implementation Guide"
description: "This is a FHIR Implementation Guide for the project of University of the Philippines Manila entitled Monitoring the Chronic Viral Hepatitis Treatment Cascade Through Electronic Medical Records in the Philippines which is being funded by Gilead Sciences, coursed through the UP Manila Development Fund"
license: CC0-1.0
publisher:
  name: UP Manila Viral Hepatitis Project
  url: http://ehealth4hepatitis.ph
email: info@ehealth4hepainformatics.ph
# contact:
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
# experimental: true
dependencies:
theme: jekyll-theme-minimal
 
